name: Heroku Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests (if any)
        run: |
          echo "No tests yet"
          
      - name: Get version
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || git rev-parse --short HEAD)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/ezo-redactify.git HEAD:main --force
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          
      - name: Set version on Heroku
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          curl -X PATCH https://api.heroku.com/apps/ezo-redactify/config-vars \
            -H "Accept: application/vnd.heroku+json; version=3" \
            -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"APP_VERSION": "${{ steps.version.outputs.version }}"}'