name: Heroku Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests (if any)
        run: |
          echo "No tests yet"
          
      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/ezo-redactify.git HEAD:main --force
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}